#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

sh /etc/init.d/rc.mc_defaults

#set MIXER quad_w
set MAV_TYPE 23

set MIXER_FILE etc/mixers-sitl/quad_x_vtol.main.mix
set MIXER custom
